name: cloud
description: "A WeatherApp with Flutter"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  gap: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/en/
    - assets/icons/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Glory
    fonts:
      - asset: assets/fonts/en/Glory-Regular.ttf
        weight: 400
      - asset: assets/fonts/en/Glory-Light.ttf
        weight: 300
      - asset: assets/fonts/en/Glory-Medium.ttf
        weight: 500
      - asset: assets/fonts/en/Glory-Bold.ttf
        weight: 700
      - asset: assets/fonts/en/Glory-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/en/Glory-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/en/Glory-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/en/Glory-LightItalic.ttf
        weight: 300
        style: italic
          
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
